server:
  port: 8888

spring:
  application:
    name: ead-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/fabio-nobre/proj-config-server-repo
          default-label: main
          username: fabio-nobre
          password: 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
ead:
  serviceRegistry:
    username: serviceregistry
    password: 'ead123sr'

eureka:
  client:
    serviceUrl:
      defaultZone: 'http://${ead.serviceRegistry.username}:${ead.serviceRegistry.password}@localhost:8761/eureka'
  instance:
    hostname: localhost


