server:
  port: 8888

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/fabio-nobre/proj-config-server-repo
          default-label: main
          username: fabio-nobre
          password: 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

ead:
  configServer:
    username: configserver
    password: 'ead123cs'
  serviceRegistry:
    username: serviceregistry
    password: 'ead123sr'

eureka:
  client:
    serviceUrl:
      defaultZone: 'http://${ead.serviceRegistry.username}:${ead.serviceRegistry.password}@localhost:8761/eureka'
  instance:
    hostname: localhost


