server:
  port: 8888

spring:
  application:
    name: ead-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/fabio-nobre/proj-config-server-repo
          default-label: main
          username: fabio-nobre
          password: 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

eureka:
  client:
    serviceUrl:
      defaultZone: 'http://localhost:8761/eureka'
  instance:
    hostname: localhost


